### ISSUE TITLE
Publish on pypi automatically on release

### ISSUE THREAD

**Issue by sp1thas** [sphinx-contrib/prefectviz#4]
Create a new github workflow in order to build and publish the module on [pypi](https://pypi.org/). I propose to use [this](https://github.com/pypa/gh-action-pypi-publish) github action. The required `PYPI_API_TOKEN` has been configured.

Make sure that the new workflow will be triggered only when a new version is released, to achieve such thing, the following approach could be used:

_.github/workflows/pypi.yml:_
```
[...]
on:
  release:
    types: [created]
[...]
```

**Comment by RishiKumarRay** [comment]
@sp1thas please review
